model: ./model.yaml

optimizer:
  name: AdamW
  kwargs:
    lr: 1  # Will be multiplied by scheduler
    weight_decay: 0.01
    amsgrad: True

lr_scheduler:
  name: Trapezoidal
  kwargs:
    min_lr: 0
    max_lr: 1e-4
    warmup_steps: 50_000
    annealing_steps: 1_00_000
    total_steps: 5_00_000

batch_size: 128

train_dataset: ./dataset_train.yaml
val_dataset: "./dataset_val.yaml"
val_batch_size: 128
val_size: 1_000

steps: 5_00_000
device: cuda