defaults:
  data_source: &brute_force_fastsrb_source
    type: fastsrb
    benchmark_path: "{{ROOT}}/data/ansr-data/test_set/fastsrb/expressions.yaml"
    datasets_per_expression: 10
    support_points: 512
    sample_points: 1024
    method: random
    max_trials: 100
    incremental: false
    random_state: 42
    noise_level: 0.0
  model_adapter: &brute_force_adapter
    type: brute_force
    simplipy_engine: "dev_7-3"
    skeleton_pool: "{{ROOT}}/data/ansr-data/test_set/fastsrb/skeleton_pool_max8"
    max_expressions: 10000
    max_length: null
    include_constant_token: true
    ignore_holdouts: true
    n_restarts: 8
    refiner_method: curve_fit_lm
    refiner_p0_noise: normal
    refiner_p0_noise_kwargs:
      loc: 0.0
      scale: 5
    numpy_errors: ignore
    parsimony: 0.05
  runner: &brute_force_fastsrb_runner
    limit: null
    save_every: 64
    resume: true

experiments:
  brute_force_fastsrb_max_expressions_00001:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 1
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00001.pkl"

  brute_force_fastsrb_max_expressions_00002:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 2
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00002.pkl"

  brute_force_fastsrb_max_expressions_00004:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 4
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00004.pkl"

  brute_force_fastsrb_max_expressions_00008:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 8
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00008.pkl"

  brute_force_fastsrb_max_expressions_00016:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 16
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00016.pkl"

  brute_force_fastsrb_max_expressions_00032:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 32
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00032.pkl"

  brute_force_fastsrb_max_expressions_00064:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 64
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00064.pkl"

  brute_force_fastsrb_max_expressions_00128:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 128
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00128.pkl"

  brute_force_fastsrb_max_expressions_00256:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 256
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00256.pkl"

  brute_force_fastsrb_max_expressions_00512:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 512
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_00512.pkl"

  brute_force_fastsrb_max_expressions_01024:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 1024
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_01024.pkl"

  brute_force_fastsrb_max_expressions_02048:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 2048
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_02048.pkl"

  brute_force_fastsrb_max_expressions_04096:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 4096
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_04096.pkl"

  brute_force_fastsrb_max_expressions_08192:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 8192
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_08192.pkl"

  brute_force_fastsrb_max_expressions_16384:
    run:
      data_source: *brute_force_fastsrb_source
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 16384
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_16384.pkl"

  brute_force_fastsrb_max_expressions_65536:
    run:
      data_source:
        <<: *brute_force_fastsrb_source
        datasets_per_expression: 5
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 65536
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_65536.pkl"

  brute_force_fastsrb_max_expressions_262144:
    run:
      data_source:
        <<: *brute_force_fastsrb_source
        datasets_per_expression: 5
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 262144
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_262144.pkl"

  brute_force_fastsrb_max_expressions_1048576:
    run:
      data_source:
        <<: *brute_force_fastsrb_source
        datasets_per_expression: 1
      model_adapter:
        <<: *brute_force_adapter
        max_expressions: 1048576
      runner:
        <<: *brute_force_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/brute_force/fastsrb/max_expressions_1048576.pkl"
