defaults:
  data_source: &pysr_fastsrb_source
    type: fastsrb
    benchmark_path: "{{ROOT}}/data/ansr-data/test_set/fastsrb/expressions.yaml"
    datasets_per_expression: 10
    support_points: 512
    sample_points: 1024
    method: random
    max_trials: 100
    incremental: false
    random_state: 42
    noise_level: 0.0
  model_adapter: &pysr_adapter
    type: pysr
    timeout_in_seconds: 3600
    niterations: 1
    padding: false
    use_mult_div_operators: false
    simplipy_engine: "dev_7-3"
  runner: &pysr_fastsrb_runner
    limit: null
    save_every: 4
    resume: true

experiments:
  pysr_fastsrb_iter_00001:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 1
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00001.pkl"

  pysr_fastsrb_iter_00002:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 2
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00002.pkl"

  pysr_fastsrb_iter_00004:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 4
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00004.pkl"

  pysr_fastsrb_iter_00008:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 8
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00008.pkl"

  pysr_fastsrb_iter_00016:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 16
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00016.pkl"

  pysr_fastsrb_iter_00032:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 32
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00032.pkl"

  pysr_fastsrb_iter_00064:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 64
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00064.pkl"

  pysr_fastsrb_iter_00128:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 128
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00128.pkl"

  pysr_fastsrb_iter_00256:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 256
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00256.pkl"

  pysr_fastsrb_iter_00512:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 512
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_00512.pkl"

  pysr_fastsrb_iter_01024:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 1024
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_01024.pkl"

  pysr_fastsrb_iter_04096:
    run:
      data_source:
        <<: *pysr_fastsrb_source
        datasets_per_expression: 5
      model_adapter:
        <<: *pysr_adapter
        timeout_in_seconds: 10000
        niterations: 4096
      runner:
        <<: *pysr_fastsrb_runner
        save_every: 1
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_04096.pkl"

  pysr_fastsrb_iter_16384:
    run:
      data_source:
        <<: *pysr_fastsrb_source
        datasets_per_expression: 5
      model_adapter:
        <<: *pysr_adapter
        timeout_in_seconds: 10000
        niterations: 16384
      runner:
        <<: *pysr_fastsrb_runner
        save_every: 1
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_16384.pkl"

  pysr_fastsrb_iter_65536:
    run:
      data_source:
        <<: *pysr_fastsrb_source
        datasets_per_expression: 1
      model_adapter:
        <<: *pysr_adapter
        timeout_in_seconds: 20000
        niterations: 65536
      runner:
        <<: *pysr_fastsrb_runner
        save_every: 1
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_65536.pkl"