defaults:
  data_source: &pysr_fastsrb_source
    type: fastsrb
    benchmark_path: "{{ROOT}}/data/ansr-data/test_set/fastsrb/expressions.yaml"
    datasets_per_expression: 10
    support_points: 512
    sample_points: 1024
    method: random
    max_trials: 100
    incremental: false
    random_state: 42
    noise_level: 0.0
  model_adapter: &pysr_adapter
    type: pysr
    timeout_in_seconds: 10000
    niterations: 1
    padding: false
    use_mult_div_operators: false
    simplipy_engine: "dev_7-3"
  runner: &pysr_fastsrb_runner
    limit: null
    save_every: 1
    resume: true

experiments:
  pysr_fastsrb_iter_04096:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 4096
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_04096.pkl"
  pysr_fastsrb_iter_16384:
    run:
      data_source: *pysr_fastsrb_source
      model_adapter:
        <<: *pysr_adapter
        niterations: 16384
      runner:
        <<: *pysr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/pysr/fastsrb/niter_16384.pkl"