defaults:
  data_source: &pysr_v23_source
    type: skeleton_dataset
    dataset: "{{ROOT}}/configs/v23.0-3M/dataset_val.yaml"
    n_support: 512
    noise_level: 0.0
    preprocess: false
    device: cpu
    datasets_per_expression: 10
  max_trials: 100
  model_adapter: &pysr_adapter
    type: pysr
    timeout_in_seconds: 3600
    niterations: 128
    padding: false
    use_mult_div_operators: false
    simplipy_engine: "dev_7-3"
  runner: &pysr_v23_runner
    limit: 1000
    save_every: 4
    resume: true

experiments:
  pysr_v23_noise_0p000:
    run:
      data_source: *pysr_v23_source
      model_adapter: *pysr_adapter
      runner:
        <<: *pysr_v23_runner
        output: "{{ROOT}}/results/evaluation/noise_sweep/pysr/v23_val/noise_0p000.pkl"

  pysr_v23_noise_0p001:
    run:
      data_source:
        <<: *pysr_v23_source
        noise_level: 0.001
      model_adapter: *pysr_adapter
      runner:
        <<: *pysr_v23_runner
        output: "{{ROOT}}/results/evaluation/noise_sweep/pysr/v23_val/noise_0p001.pkl"

  pysr_v23_noise_0p010:
    run:
      data_source:
        <<: *pysr_v23_source
        noise_level: 0.01
      model_adapter: *pysr_adapter
      runner:
        <<: *pysr_v23_runner
        output: "{{ROOT}}/results/evaluation/noise_sweep/pysr/v23_val/noise_0p010.pkl"

  pysr_v23_noise_0p100:
    run:
      data_source:
        <<: *pysr_v23_source
        noise_level: 0.1
      model_adapter: *pysr_adapter
      runner:
        <<: *pysr_v23_runner
        output: "{{ROOT}}/results/evaluation/noise_sweep/pysr/v23_val/noise_0p100.pkl"