simplipy_engine: 'dev_7-3'
tokenizer: './tokenizer.yaml'

pre_encoder_noise_scale: 0.1

encoder_max_n_variables: 11
encoder_dim: 640
encoder_n_heads: 10
encoder_n_isab: 2
encoder_n_sab: 2
encoder_n_inducing_points: 64
encoder_n_seeds: 64
encoder_ffn_hidden_dim: 1920
encoder_dropout: 0.1
encoder_attn_norm: 'rms_set'
encoder_ffn_norm: 'rms_set'
encoder_output_norm: 'rms_set'

decoder_input_dim: 640
decoder_model_dim: 640
decoder_n_heads: 10
decoder_n_layers: 5
decoder_max_seq_len: 128
decoder_ffn_hidden_dim: 1920
decoder_dropout: 0.1
decoder_block_self_attn_norm: 'rms'
decoder_block_cross_attn_norm: 'rms'
decoder_block_ffn_norm: 'rms'
decoder_cross_attn_kv_norm: 'rms'
decoder_output_norm: 'rms'
decoder_use_rope_self_attn: true
decoder_use_rope_cross_attn: false

use_checkpointing: false