noise_level: 0.0
complexity: 'none'
preprocess: false
device: cuda
refiner_workers: null

n_restarts: 8
refiner_method: 'curve_fit_lm'
refiner_p0_noise: 'normal'
refiner_p0_noise_kwargs:
  loc: 0.0
  scale: 5
parsimony: 0.05

generation_config:
  method: 'softmax_sampling'
  kwargs:
    choices: 256
    top_k: 0
    top_p: 1
    max_len: 32
    mini_batch_size: 128
    temperature: 1
    valid_only: true
    simplify: true
    unique: true

fastsrb:
  benchmark_path: 'data/fastsrb/expressions.yaml'
  count: 10
  n_points: 512
  method: 'random'
  max_trials: 100
  incremental: false
  random_state: null
  equations: null
