run:
  data_source:
    type: skeleton_dataset
    dataset: "{{ROOT}}/configs/v21.x_dataset/dataset_val.yaml"
    n_support: 512
    noise_level: 0.0
    preprocess: false
    device: cuda
    datasets_per_expression: 1
  model_adapter:
    type: flash_ansr
    model_path: "{{ROOT}}/models/ansr-models/v21.0-370M"
    evaluation_config: "{{ROOT}}/configs/v21.0-370M/evaluation.yaml"
    complexity: none
    device: cuda
    generation_overrides:
      kwargs:
        choices: 4
  runner:
    limit: 64
    save_every: 16
    resume: false
    output: "{{ROOT}}/results/evaluation/quick/v21.0-370M/v23_val.pkl"
