simplipy_engine: 'dev_7-3'
tokenizer: './tokenizer.yaml'

pre_encoder_noise_scale: 0.1

encoder_max_n_variables: 20
encoder_dim: 1280
encoder_n_heads: 20
encoder_n_isab: 10
encoder_n_sab: 10
encoder_n_inducing_points: 128
encoder_n_seeds: 128
encoder_ffn_hidden_dim: 3840
encoder_dropout: 0.1
encoder_attn_norm: 'rms_set'
encoder_ffn_norm: 'rms_set'
encoder_output_norm: 'rms_set'

decoder_input_dim: 1280
decoder_model_dim: 1280
decoder_n_heads: 20
decoder_n_layers: 20
decoder_max_seq_len: 128
decoder_ffn_hidden_dim: 3840
decoder_dropout: 0.1
decoder_block_self_attn_norm: 'rms'
decoder_block_cross_attn_norm: 'rms'
decoder_block_ffn_norm: 'rms'
decoder_cross_attn_kv_norm: 'rms'
decoder_output_norm: 'rms'
decoder_use_rope_self_attn: true
decoder_use_rope_cross_attn: false

use_checkpointing: false