contrastive_encoder: ./contrastive_encoder.yaml

optimizer:
  name: AdamW
  kwargs:
    lr: 1  # Will be multiplied by scheduler
    betas: [0.9, 0.95]

lr_scheduler:
  name: Trapezoidal
  kwargs:
    min_lr: 0
    max_lr: 2.5e-4
    warmup_steps: 50_000
    annealing_steps: 100_000
    total_steps: 500_000

batch_size: 256

train_dataset: ./dataset_train.yaml
val_dataset: "./dataset_val.yaml"
val_batch_size: 256
val_size: 100_000

compile_mode: 'reduce-overhead'
gradient_checkpointing: False

wandb_watch_log: null
wandb_watch_log_freq: 1000

steps: 500_000
device: cuda

contrastive_temperature:
  - [0, 0.5]
  - [500_000, 0.05]

contrastive_views: 2