simplipy_engine: 'dev_7-3'
holdout_pools: ["{{ROOT}}/data/ansr-data/v22.4/skeleton_pool_val/", "{{ROOT}}/data/ansr-data/test_set/soose_nc/skeleton_pool/", "{{ROOT}}/data/ansr-data/test_set/feynman/skeleton_pool/", "{{ROOT}}/data/ansr-data/test_set/nguyen/skeleton_pool/", "{{ROOT}}/data/ansr-data/test_set/pool_15_10/skeleton_pool/"]

sample_strategy:
  n_operator_distribution: "length_exponential"
  min_operators: 0
  max_operators: 25
  power: 0.7
  lambda: 1
  max_length: 51
  max_tries: 4
  independent_dimensions: true

allow_nan: false
simplify: true

literal_prior:
  name: 'normal'
  kwargs:
    loc: 0
    scale: 5

support_sampler:
  support_prior:
    name: "sampler"
    kwargs:
      base_dist_name: "uniform"
      base_kwargs:
        min_value: -30
        max_value: 30
      param_samplers:
        low:
          name: "normal"
          kwargs: {loc: 0, scale: 10}
        high:
          name: "normal"
          kwargs: {loc: 0, scale: 10}
  n_support_prior:
    name: "uniform"
    kwargs:
      low: 1
      high: 1024
      min_value: 1
      max_value: 1024

variables: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', 'x22', 'x23', 'x24', 'x25']

operator_weights:
  "+": 10
  "-": 10
  "*": 10
  "/": 10
  abs: 1
  inv: 1
  neg: 1
  pow2: 1
  pow3: 1
  pow4: 1
  pow5: 1
  pow1_2: 1
  pow1_3: 1
  pow1_4: 1
  pow1_5: 1
  sin: 1
  cos: 1
  tan: 1
  asin: 1
  acos: 1
  atan: 1
  sinh: 1
  cosh: 1
  tanh: 1
  asinh: 1
  acosh: 1
  atanh: 1
  exp: 1
  log: 1
  mult2: 1
  mult3: 1
  mult4: 1
  mult5: 1
  div2: 1
  div3: 1
  div4: 1
  div5: 1
