simplipy_engine: './simplipy_engine.yaml'
tokenizer: './tokenizer.yaml'

# L
encoder_max_n_variables: 11
encoder_dim: 1024
encoder_n_heads: 16
encoder_n_isab: 10
encoder_n_sab: 3
encoder_n_inducing_points: 96
encoder_n_seeds: 96
encoder_ffn_hidden_dim: 2736
encoder_dropout: 0.1
encoder_attn_norm: 'none'
encoder_ffn_norm: 'none'
encoder_output_norm: 'none'

decoder_input_dim: 1024
decoder_model_dim: 1024
decoder_n_heads: 16
decoder_n_layers: 15
decoder_max_seq_len: 128
decoder_ffn_hidden_dim: 2736
decoder_dropout: 0.1
decoder_block_self_attn_norm: 'rms'
decoder_block_cross_attn_norm: 'rms'
decoder_block_ffn_norm: 'rms'
decoder_cross_attn_kv_norm: 'none'
decoder_output_norm: 'rms'
