simplipy_engine: './simplipy_engine.yaml'
tokenizer: './tokenizer.yaml'

# L
encoder_max_n_variables: 11
encoder_dim: 1024
encoder_n_heads: 16
encoder_n_isab: 10
encoder_n_sab: 3
encoder_n_inducing_points: 96
encoder_n_seeds: 96
encoder_ffn_hidden_dim: 2736
encoder_dropout: 0.1
encoder_attn_norm: 'none'
encoder_ffn_norm: 'none'
encoder_output_norm: 'none'

decoder_input_dim: 1024
decoder_model_dim: 1024
decoder_n_heads: 16
decoder_n_layers: 15
decoder_max_seq_len: 128
decoder_ffn_hidden_dim: 2736
decoder_dropout: 0.1


# L+
# encoder_max_n_variables: 11
# encoder_dim: 1152
# encoder_n_heads: 18
# encoder_n_isab: 11
# encoder_n_sab: 4
# encoder_n_inducing_points: 108
# encoder_n_seeds: 108
# encoder_ffn_hidden_dim: 3078
# encoder_dropout: 0.1

# decoder_input_dim: 1152
# decoder_model_dim: 1152
# decoder_n_heads: 18
# decoder_n_layers: 18
# decoder_max_seq_len: 128
# decoder_ffn_hidden_dim: 3078
# decoder_dropout: 0.1

# XL
# encoder_max_n_variables: 11
# encoder_dim: 1280
# encoder_n_heads: 20
# encoder_n_isab: 16
# encoder_n_sab: 4
# encoder_n_inducing_points: 128
# encoder_n_seeds: 128
# encoder_ffn_hidden_dim: 3416
# encoder_dropout: 0.1

# decoder_input_dim: 1280
# decoder_model_dim: 1280
# decoder_n_heads: 20
# decoder_n_layers: 20
# decoder_max_seq_len: 128
# decoder_ffn_hidden_dim: 3416
# decoder_dropout: 0.1