encoder_max_n_variables: 11  # includes the dependent variable

pre_encoder_input_type: "ieee-754-32"
pre_encoder_support_nan: False

encoder: "SetTransformer"
encoder_kwargs:
  hidden_size: 512
  n_enc_isab: 8
  n_dec_sab: 4
  n_induce: 64
  n_heads: 8
  layer_norm: False
  n_seeds: 64

size: 512
decoder_n_heads: 8
decoder_ff_size: 512
decoder_dropout: 0.1
decoder_n_layers: 8

learnable_positional_embeddings: False
max_input_length: null

simplipy_engine: './simplipy_engine.yaml'
tokenizer: './tokenizer.yaml'